conf.py:
  copyright: 2017
  project: Pages Tree Icons
  version: 1.2
  release: 1.2.2
  latex_documents:
  - - Index
    - rt_pages_tree_icons.tex
    - A new Backend-Module to have a more comprehensive Page treeview.
    - Regis TEDONE
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
